### ISSUE TITLE
Support TM2020 inputs

### ISSUE THREAD

**Issue by Chris92de** [bigbang1112-cz/clip-input#10]
Since TM2020 inputs can now be extracted with GBX.net v1.1.1 and above, please support this game in this tool.
https://github.com/BigBang1112/gbx-net

**Comment by MicroMelone** [comment]
Yes please, I'd love to be able to show inputs in tm 2020 rendered replays <3

**Comment by BigBang1112** [comment]
This repo will have a new branch soon with Clip Input 2 progress. No rush, it's gonna be worth it.

**Comment by BigBang1112** [comment]
Solved as of today
